language: python
python:
- '3.4'
sudo: false
install:
- pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst
script:
- script/cibuild
env:
  global:
  - secure: KjcMRqgsg0gqK26cAaob/oyDDd3VrtZKA8tbVh+9feKoDvM7iLz6h7mB1LDBw237jYls9JVF4OtHidx7ySYhOF/VrXoqye/tLF5Z9Eve7htTXYvOG2B5c0SAGIKTuBv5kWX0PH/H9f6Oz2Rkvg1PaKv2/MmNVZPytcNPIGUid4A=
  - secure: oFuGz2BHEB8iDwqHbxsGjzQBh+VJ+hTvWxGFX+1PTu6tMiCpa1unf0jrecLVEJuaaJ7uhzhsNBb8niXtwI+wtBpX/mzfsgjL6Lc32Q2c+HHeNl/f73aGz/uIYAymD0XJCcgK225/SbppJMHWqPVvox0RzWFX1Kp6H3xrYhcql0g=
  - secure: P/ygDTZohpAwjdEOWDJxnWJyY4SGr/TJ5hnSswsiYXpgUZl/2ypgZPL0PFSgkx8IgKy1mt0zty6oK0iMLaOEzAjfpZpdtP156UBrm3/vc4YvpEnFQS1P9UcbbJWVX2tfOFGg/mOqd4N6m/Zn3rogDkx6vq04d1P4H+soJg+AVmQ=
notifications:
  slack:
    secure: U6395pEPp+TAiMYackkfHtZkt36G+0KskEvKi4gVtnt9Wy/QXfTPHzJd5sgsxtYzUjbkpAzHO45WqeuKQ2+2cojQqdmgGLD3sm7jo3upHG0TiLvj5ncOGQPNiksSYtny7yUpl8jvi2ceRJQel1JEBFjClCbWsPBFtP4S/23iYMU=
