source: ./content
destination: ./how-to

baseurl: "/how-to/"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: "/:basename/"


assets:
  sources:
    - _assets/img
