title: <SITE TITLE>
email: <TEAM EMAIL>
description: >
  <MULTI-LINE DESCRIPTION>
baseurl: "/<ORG_NAME_OR_USERNAME>/<REPO_NAME>"
url: "https://pages.github.rackspace.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
